// Mock data extracted from API routes for build-time rendering

export const productData = {
  id: '60f1b2b5c8d4a1b2c3d4e5f6',
  title: 'Google Play Gift Card',
  description:
    'A Google Play gift card is a prepaid credit that can be used to make purchases within the Google Play Store. It allows users to add credit to their Google Play balance, which can be used to buy apps, games, music, books, and other items available on the platform.',
  image: '/images/products/google-play-gift-card.png',
  backgroundImage: '/images/backgrounds/google-play-gift-card.png',
  cardImage: '',
  price: 35.0,
}

export const mockYouMayAlsoLikeProducts = [
  {
    id: 'mock_1',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/conan-exiles.png',
    price: 80.0,
  },
  {
    id: 'mock_2',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/detroit-become-human.png',
    price: 80.0,
  },
  {
    id: 'mock_3',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/mutant-year-zero.png',
    price: 80.0,
  },
  {
    id: 'mock_4',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/this-war-of-mine.png',
    price: 80.0,
  },
  {
    id: 'mock_5',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/payday-2.png',
    price: 80.0,
  },
  {
    id: 'mock_6',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/fishing-clash.png',
    price: 80.0,
  },
  {
    id: 'mock_7',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/bug-fables.png',
    price: 80.0,
  },
  {
    id: 'mock_8',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/grabi-toons.png',
    price: 80.0,
  },
]

export const mockLastSeenProducts = [
  {
    id: 'mock_1',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/payday-2.png',
    price: 80.0,
  },
  {
    id: 'mock_2',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/fishing-clash.png',
    price: 80.0,
  },
  {
    id: 'mock_3',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/bug-fables.png',
    price: 80.0,
  },
  {
    id: 'mock_4',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/grabi-toons.png',
    price: 80.0,
  },
  {
    id: 'mock_5',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/conan-exiles.png',
    price: 80.0,
  },
  {
    id: 'mock_6',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/detroit-become-human.png',
    price: 80.0,
  },
  {
    id: 'mock_7',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/mutant-year-zero.png',
    price: 80.0,
  },
  {
    id: 'mock_8',
    title: 'Conan Exiles: The Riddle of Steel Ultimate Deluxe Collection',
    description: '',
    image: '',
    backgroundImage: '',
    cardImage: '/images/cards/this-war-of-mine.png',
    price: 80.0,
  },
]
